
filebeat.inputs:


- type: log
  enabled: true
  paths:
    - "../multiversa-/*.log"
  multiline.pattern: "^([0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{3})|^[=]{57}$"
  multiline.negate: true
  multiline.match: after

- type: log
  enabled: true
  paths:
    - "../multiversa-/*.json"
  multiline.pattern: "^{"
  multiline.negate: true
  multiline.match: after
  multiline.max_lines: 300000000
  multiline.max_bytes: 1000 MiB

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml

  reload.enabled: false


setup.template.settings:
  index.number_of_shards: 1
#----------------------------- Logstash output --------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["127.0.0.1:5044"]
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~